// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];

  // If environment variables are missing, we provide a dummy client that warns instead of crashing.
  // This prevents the black screen / boot deadlock while preserving the security constraint.
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Missing configuration. App will run in limited local mode. " +
        "Connect Supabase in Lovable Cloud to enable Auth and Cloud Sync.",
    );

    // Return a proxy that fails gracefully on actual calls rather than on boot
    return new Proxy({} as any, {
      get(_, prop) {
        if (prop === "auth") {
          return {
            getSession: async () => ({ data: { session: null }, error: null }),
            onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
            getUser: async () => ({ data: { user: null }, error: null }),
          };
        }
        if (prop === "from")
          return () => ({
            select: () => ({
              order: () => ({
                limit: () =>
                  Promise.resolve({
                    data: [],
                    error: { message: "Supabase not configured", code: "CONFIG_ERROR" },
                  }),
              }),
            }),
            insert: () =>
              Promise.resolve({
                data: null,
                error: { message: "Supabase not configured", code: "CONFIG_ERROR" },
              }),
            update: () =>
              Promise.resolve({
                data: null,
                error: { message: "Supabase not configured", code: "CONFIG_ERROR" },
              }),
            delete: () =>
              Promise.resolve({
                data: null,
                error: { message: "Supabase not configured", code: "CONFIG_ERROR" },
              }),
          });
        return () => {};
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
